### ISSUE TITLE
std::format is not implemented

### ISSUE THREAD

**Issue by theundergroundsorcerer** [Apress/beginning-cpp20#31]
None of the major vendors implements the format header yet. Hence, none of the book examples that use them work at the moment. There is a workaround by using fmt library, however requires extra work. Please update the appendix and provide clear instructions to install the fmt library to make the examples work. Or replace the std::format examples with stream formatting.

No offense, but has anyone tried to compile the source code? This is a minimum effort required to do when writing a book aimed at "beginners".

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
I have the same question when I was reading the book. After some investigation, I found the fmt library. I installed it through the vcpkg package manager and it works well.

**Comment by theundergroundsorcerer** [comment]
I did not say it was an unsolvable problem. However, it should at be mentioned, as the book heavily relies on std::format (fmt::format). It is not.

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
I agree. Actually I was thinking what compiler Horton is using when I was reading the book.

**Comment by Peter-VanWeert** [comment]
You are absolutely right, this a massive oversight. Apologies. It was on the top of my TODO list, but then I got busy with work and forgot about it. But that does not help you, of course, and expecting someone that is just beginning C++ to figure out the workaround is not OK. I will add explanations on how to work around this asap!

**Comment by Peter-VanWeert** [comment]
I explained how you can work around `std::format()` (and some other C++20 features) not compiling to a `Workarounds` directory of the source repo. If anything is not clear, do not hesitate to let me know! Again: my sincere apologies for any inconvenience caused by me not adding this months ago already...
