### ISSUE TITLE
Exercise 2-4 code wrong?

### ISSUE THREAD

**Issue by positivevibes123** [Apress/beginning-cpp20#35]
For the exercise 2-4 answer, a person's height in meters is calculated as this:

 h_meters { meters_per_foot * h_feet + h_inches / inches_per_foot };

This converts the recorded feet to meters, but then converts the recorded inches to feet and adds feet to meters, which doesn't make sense. I believe this leads to incorrect BMI values.

It should be this:

h_meters { meters_per_foot * (h_feet + h_inches / inches_per_foot) };

**Comment by Peter-VanWeert** [comment]
You were, of course, right. Fixed now. Thanks for reporting this, and sorry it took me this long to respond!
